/// Flutter icons CustomIconStar
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIconStar
///      fonts:
///       - asset: fonts/CustomIconStar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIconStar {
  CustomIconStar._();

  static const _kFontFam = 'CustomIconStar';

  static const IconData stars4 = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData stars5 = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData stars1 = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData stars2 = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData stars3 = IconData(0xe805, fontFamily: _kFontFam);
}
