/// Flutter icons HelpIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HelpIcon
///      fonts:
///       - asset: fonts/HelpIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HelpIcon {
  HelpIcon._();

  static const _kFontFam = 'HelpIcon';

  static const IconData question_sign = IconData(0xe800, fontFamily: _kFontFam);
}
