/// Flutter icons HomeIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeIcons
///      fonts:
///       - asset: fonts/HomeIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class HomeIcons {
  HomeIcons._();

  static const _kFontFam = 'HomeIcons';

  static const IconData help_circled = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData telescope = IconData(0xe801, fontFamily: _kFontFam);
}
