/// Flutter icons HomeDrawerIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeDrawerIcon
///      fonts:
///       - asset: fonts/HomeDrawerIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeDrawerIcon {
  HomeDrawerIcon._();

  static const _kFontFam = 'HomeDrawerIcon';

  static const IconData home_drawer = IconData(0xe801, fontFamily: _kFontFam);
}
