/// Flutter icons InformationIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InformationIcon
///      fonts:
///       - asset: fonts/InformationIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InformationIcon {
  InformationIcon._();

  static const _kFontFam = 'InformationIcon';

  static const IconData information = IconData(0xe800, fontFamily: _kFontFam);
}
