/// Flutter icons InfoIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InfoIcon
///      fonts:
///       - asset: fonts/InfoIcon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class InfoIcon {
  InfoIcon._();

  static const _kFontFam = 'InfoIcon';

  static const IconData help = IconData(0xf128, fontFamily: _kFontFam);
}
